version: '3.8'

services:
    kali-linux-c:
        image: kalilinux/kali-rolling
        container_name: kali-linux-c
        stdin_open: true  # Equivalent to -i
        tty: true         # Equivalent to -t
        restart: unless-stopped
        networks:
            hacking-lab:
                ipv4_address: 172.20.0.5  # Fixed IP for kali-linux-c container

    kali-linux-vc:
        image: lscr.io/linuxserver/kali-linux
        container_name: kali-linux-vc
        security_opt: # optional
            - seccomp=unconfined
        environment:
            - PUID=197609 # Replace with your pc id (that can get using this command 'id')
            - PGID=197609 # Replace with your pc id (that can get using this command 'id')
            - TZ=Etc/UTC
            - SUBFOLDER=/
            - TITLE=Kali-Linux-VC
        ports:
            - 3000:3000
            - 3001:3001
        dvice: dev/dir:/dve/dir # optional (This will connect your GPU with Container and this will work with only Linux)  
        shm_size: "1gb"
        restart: unless-stopped
        networks:
            hacking-lab:
                ipv4_address: 172.20.0.10  # Fixed IP for kali-linux-vc container

    vulnerable:
        image: vulnerables/web-dvwa
        networks:
            - hacking-lab
        deploy:
            restart_policy:
                condition: on-failure

networks:
    hacking-lab:
        driver: bridge
        internal: true # Comment this if you using kali-linux-vc or if you need to connect this network and internet
        ipam:
            config:
                - subnet: 172.20.0.0/24
